# Generated by Django 3.0.3 on 2020-07-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bid_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_Listing',
            new_name='Listing',
        ),
    ]
