# Generated by Django 3.0.3 on 2020-07-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='likers',
            new_name='liker',
        ),
    ]
