# Generated by Django 3.0.3 on 2020-08-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgamgo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamesCompleted',
            new_name='Games',
        ),
    ]
