# Generated by Django 3.0.3 on 2020-08-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgamgo', '0002_auto_20200804_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
