# Generated by Django 3.0.3 on 2020-08-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgamgo', '0003_auto_20200804_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
